---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: immjackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=false #optional
#      - RUN_OPTS=<run options here> #optional
#   volumes:
#      - <path to data>:/config
#      - <path to blackhole>:/downloads
    ports:
      - 12451:12451
    restart: unless-stopped
